#!/bin/bash -x
VERSION=1.0.1

# Salmon Vault JavaFX
OUTPUT_ROOT=../../../output
OUTPUT_DIR=$OUTPUT_ROOT/java
SALMON_TUNNEL_JAR=./build/libs/SalmonTunnel-$VERSION.jar
SALMON_LIBS_DIR=./libs
SALMON_SCRIPTS_DIR=./scripts

PACKAGES_DIR=app_package
SALMON_TUNNEL=salmon-tunnel
SALMON_TUNNEL_PACKAGE_NAME=$SALMON_TUNNEL

mkdir -p $PACKAGES_DIR
rm -rf ./$PACKAGES_DIR/*

mkdir -p $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME
rm -rf ./$PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/*

mkdir -p $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/salmon/
cp -r $SALMON_LIBS_DIR/* $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/salmon/
cp -r $SALMON_TUNNEL_JAR $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/salmon/

cp -r $SALMON_SCRIPTS_DIR/* $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/
cp README.txt $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME/

cd $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME
zip -r ../$SALMON_TUNNEL_PACKAGE_NAME.zip *
cd ../../
mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_TUNNEL_PACKAGE_NAME.zip $OUTPUT_DIR

